# Generated by Django 4.0.4 on 2022-06-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='img',
            field=models.CharField(max_length=550),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('dogs', models.ManyToManyField(to='main_app.dog')),
            ],
        ),
    ]
