# Generated by Django 4.0.4 on 2022-06-02 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_dog_img_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rescue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rescues', to='main_app.dog')),
            ],
        ),
    ]
